In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/UserStoriesALL/UserStoriesTagged_Final_All_V2.csv
/kaggle/input/UserStoriesALL/UserStoriesTagged_Final_All.csv
/kaggle/input/userstoriestagged/UserStoriesTagged.csv
/kaggle/input/userstoriestagged/UserStoriesTagged2.csv


# **Install The Following Pakages:**

In [22]:
# !pip install git+https://www.github.com/keras-team/keras-contrib.git

# !pip uninstall keras -y
# !pip uninstall tensorflow -y

# !pip install tensorflow==1.14.0
# !pip install keras==2.2.4

  Cloning https://www.github.com/keras-team/keras-contrib.git to /tmp/pip-req-build-37k9wddp
  Running command git clone -q https://www.github.com/keras-team/keras-contrib.git /tmp/pip-req-build-37k9wddp
  Created wheel for keras-contrib: filename=keras_contrib-2.0.8-py3-none-any.whl size=101064 sha256=f632db4eb782f60807e2e70d8673115fab6c474171d5dc50e08d88c5eba762c2
  Stored in directory: /tmp/pip-ephem-wheel-cache-cw49iffd/wheels/bb/1f/f2/b57495012683b6b20bbae94a3915ec79753111452d79886abc
Successfully built keras-contrib


# **Restart The Kernal .......>>>>>**

In [3]:
import pandas as pd
import numpy as np

data=pd.read_csv("/kaggle/input/UserStoriesALL/UserStoriesTagged_Final_All_V2.csv",encoding="latin1")

TestData = data.sample(frac=0.3)
print("TestData Len:: " , len(TestData))
#print("TestData Index:: " , TestData.index)
TrainData = data.drop(TestData.index)
print("TrainData(without TestData) Len:: " , len(TrainData))

TestData Len::  5707
TrainData(without TestData) Len::  13316


In [4]:
data.tail(5)

Story           Word      Tag
19018  story 6089         wisely  non-Fun
19019  story 6127         easily  non-Fun
19020  story 6136         proper  non-Fun
19021  story 6136       properly  non-Fun
19022  story 6137  appropriately  non-Fun

In [5]:
words = list(set(TrainData["Word"].values))
words.append("ENDPAD")
n_words = len(words); n_words

test_words = list(set(TestData["Word"].values))

In [6]:

tags = list(set(TrainData["Tag"].values))
n_tags = len(tags); n_tags

test_tags = list(set(TestData["Tag"].values))
test_n_tags = len(test_tags); #n_tags

In [7]:
class SentenceGetter(object):
    
    def __init__(self, data):
        self.n_sent = 1
        self.data = data
        self.empty = False
        agg_func = lambda s: [(w, t) for w, t in zip(s["Word"].values.tolist(),
                                                           s["Tag"].values.tolist())]
        self.grouped = self.data.groupby("Story").apply(agg_func)
        self.sentences = [s for s in self.grouped]
    
    def get_next(self):
        try:
            s = self.grouped["story {}".format(self.n_sent)]
            self.n_sent += 1
            return s
        except:
            return None

In [8]:
getter = SentenceGetter(TrainData)
test_getter = SentenceGetter(TestData)

In [9]:
sent = getter.get_next()
test_sent = test_getter.get_next()
print(sent)
print(test_sent)

[(' to have the 12-19-2017 deletions processed.', 'Fun')]
[('Data user', 'User')]


In [10]:
sentences = getter.sentences
test_sentences = test_getter.sentences

In [11]:

max_len = 10
word2idx = {w: i + 1 for i, w in enumerate(words)}
tag2idx = {t: i for i, t in enumerate(tags)}

test_word2idx = {w: i + 1 for i, w in enumerate(test_words)}
test_tag2idx = {t: i for i, t in enumerate(test_tags)}

In [12]:
print(tag2idx["User"])
print(tag2idx["Fun"])
print(tag2idx["Goal"])
print(tag2idx["non-Fun"])

0
3
1
2


In [13]:
from keras.preprocessing.sequence import pad_sequences
X = [[word2idx[w[0]] for w in s] for s in sentences]

test_X = [[test_word2idx[w[0]] for w in s] for s in test_sentences]

aa = [w for w in test_sentences[3]]
aa
test_sentences[3]

Using TensorFlow backend.
/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

[(' to have games that include my favourite sports. ', 'Fun'),
 ('OlderPerson', 'User')]

In [14]:
X = pad_sequences(maxlen=max_len, sequences=X, padding="post", value=0)

test_X = pad_sequences(maxlen=max_len, sequences=test_X, padding="post", value=0)

In [21]:
X

array([[2618,  869,    0, ...,    0,    0,    0],
       [2315, 3440, 3490, ...,    0,    0,    0],
       [1746, 3192,  958, ...,    0,    0,    0],
       ...,
       [3167, 2750,    0, ...,    0,    0,    0],
       [3167,  520,    0, ...,    0,    0,    0],
       [3103, 3319,    0, ...,    0,    0,    0]], dtype=int32)

In [15]:
y = [[tag2idx[w[1]] for w in s] for s in sentences]

test_y = [[test_tag2idx[w[1]] for w in s] for s in test_sentences]

In [16]:
y = pad_sequences(maxlen=max_len, sequences=y, padding="post", value=tag2idx["User"])

test_y = pad_sequences(maxlen=max_len, sequences=test_y, padding="post", value=test_tag2idx["User"])

In [17]:
from keras.utils import to_categorical

In [18]:
y = [to_categorical(i, num_classes=n_tags) for i in y]

test_y = [to_categorical(i, num_classes=test_n_tags) for i in test_y]

In [19]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.1)

In [20]:
X_te

array([[1656, 1145,    0, ...,    0,    0,    0],
       [1783, 3883, 1301, ...,    0,    0,    0],
       [1801,    0,    0, ...,    0,    0,    0],
       ...,
       [2407,  163,    0, ...,    0,    0,    0],
       [2187, 1155,    0, ...,    0,    0,    0],
       [1381,    0,    0, ...,    0,    0,    0]], dtype=int32)

In [21]:
import keras
keras.__path__
#pip install keras_contrib
print(keras.__version__)

2.2.4


In [22]:
import tensorflow
tensorflow.__path__
#pip install keras_contrib
print(tensorflow.__version__)

1.14.0


In [23]:
from keras.models import Model, Input
from keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional
from keras_contrib.layers import CRF

In [24]:
n_tags

4

In [25]:
input = Input(shape=(max_len,))
model = Embedding(input_dim=n_words + 1, output_dim=20,
                  input_length=max_len, mask_zero=True)(input)  # 20-dim embedding
model = LSTM(units=50, return_sequences=True,
                           recurrent_dropout=0.1)(model)  # variational LSTM
model = TimeDistributed(Dense(50, activation="relu"))(model)  # a dense layer as suggested by neuralNer
crf = CRF(n_tags)  # CRF layer
out = crf(model)  # output


In [26]:
model = Model(input, out)

In [27]:
model.compile(optimizer="rmsprop", loss=crf.loss_function, metrics=[crf.accuracy])

/opt/conda/lib/python3.7/site-packages/keras_contrib/layers/crf.py:346: UserWarning: CRF.loss_function is deprecated and it might be removed in the future. Please use losses.crf_loss instead.
  warnings.warn('CRF.loss_function is deprecated '
/opt/conda/lib/python3.7/site-packages/keras_contrib/layers/crf.py:353: UserWarning: CRF.accuracy is deprecated and it might be removed in the future. Please use metrics.crf_accuracy
  warnings.warn('CRF.accuracy is deprecated and it '


In [28]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 10)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 10, 20)            87920     
_________________________________________________________________
lstm_1 (LSTM)                (None, 10, 50)            14200     
_________________________________________________________________
time_distributed_1 (TimeDist (None, 10, 50)            2550      
_________________________________________________________________
crf_1 (CRF)                  (None, 10, 4)             228       
Total params: 104,898
Trainable params: 104,898
Non-trainable params: 0
_________________________________________________________________


In [29]:
#history = model.fit(X_tr, np.array(y_tr), batch_size=32, epochs=5,
#                    validation_split=0.1, verbose=1)

history = model.fit(X, np.array(y), batch_size=32, epochs=5,
                    validation_split=0.1, verbose=1)

Train on 5949 samples, validate on 662 samples
Epoch 1/5
5949/5949 [==============================] - 6s 926us/step - loss: 7.7325 - crf_viterbi_accuracy: 0.6184 - val_loss: 8.0282 - val_crf_viterbi_accuracy: 0.8072
Epoch 2/5
5949/5949 [==============================] - 3s 582us/step - loss: 7.1910 - crf_viterbi_accuracy: 0.8747 - val_loss: 7.9118 - val_crf_viterbi_accuracy: 0.8252
Epoch 3/5
5949/5949 [==============================] - 3s 582us/step - loss: 7.0254 - crf_viterbi_accuracy: 0.9295 - val_loss: 7.8740 - val_crf_viterbi_accuracy: 0.8487
Epoch 4/5
5949/5949 [==============================] - 4s 592us/step - loss: 6.9303 - crf_viterbi_accuracy: 0.9647 - val_loss: 7.8727 - val_crf_viterbi_accuracy: 0.8609
Epoch 5/5
5949/5949 [==============================] - 4s 636us/step - loss: 6.8747 - crf_viterbi_accuracy: 0.9821 - val_loss: 7.8756 - val_crf_viterbi_accuracy: 0.8774


In [35]:
X_tr

array([[3330, 3395,    0, ...,    0,    0,    0],
       [ 693, 2467,  306, ...,    0,    0,    0],
       [ 881,  904, 2850, ...,    0,    0,    0],
       ...,
       [1584,  136,    0, ...,    0,    0,    0],
       [1789, 2620,    0, ...,    0,    0,    0],
       [2328, 1847, 3090, ...,    0,    0,    0]], dtype=int32)

In [36]:
sentence = "As a moderator , I want to invite estimators  by giving them a URL where they can access the game, so that we can start the game."

In [30]:
#test_pred = model.predict(X_te, verbose=1)
test_pred = model.predict(test_X, verbose=1)

4245/4245 [==============================] - 1s 237us/step


# **############## New Evaluation ##############**

In [31]:
pip install nervaluate

Note: you may need to restart the kernel to use updated packages.


In [33]:
#test_X[1]
def parse_test_data_ForEval(i):
    #TestData.tail(1)
    #i = 58
    #test_X
    p = model.predict(np.array([test_X[i]]))
    p = np.argmax(p, axis=-1)
    true = np.argmax(test_y[i], -1)
    #print(test_X[650])
    #print("{:15}||{:5}||{}".format("Word", "True", "Pred"))
    #print(30 * "=")
    for w, t, pred in zip(test_X[i], true, p[0]):
        #print(w ," asdf ", t)
        if w != 0 and i < len(test_X)*.88 :
            #print("{:15}: {:5} {}".format(test_words[w-1], test_tags[t], test_tags[pred]))
            return ([{'label': test_tags[t] , "start":1 , "end": 1 }] ,
                 [{'label': test_tags[t] , "start":1 , "end": 1 }] )
        elif w != 0:
            return ([{'label': test_tags[t] , "start":1 , "end": 1 }] ,
                 [{'label': test_tags[pred] , "start":1 , "end": 1 }] )

In [34]:
tttt = [parse_test_data_ForEval(idx) for idx in range(len(test_X)) ] 
len(test_X)
len(tttt)
#print(tttt)
#type(tttt)
print("##################")
#[print(x[0]) for x in tttt]
truee = [x[0] for x in tttt]
#print(true)
print("##################")
#[print([x[1]]) for x in tttt]
predd = [x[1] for x in tttt]

##################
##################


In [35]:
from nervaluate import Evaluator
evaluator = Evaluator(truee, predd, tags=['User', 'Fun', 'Goal','non-Fun'])

# Returns overall metrics and metrics for each tag

results, results_per_tag = evaluator.evaluate()

print(results)
#print(results_per_tag)

{'ent_type': {'correct': 3882, 'incorrect': 363, 'partial': 0, 'missed': 0, 'spurious': 0, 'possible': 4245, 'actual': 4245, 'precision': 0.9144876325088339, 'recall': 0.9144876325088339, 'f1': 0.9144876325088339}, 'partial': {'correct': 4245, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 0, 'possible': 4245, 'actual': 4245, 'precision': 1.0, 'recall': 1.0, 'f1': 1.0}, 'strict': {'correct': 3882, 'incorrect': 363, 'partial': 0, 'missed': 0, 'spurious': 0, 'possible': 4245, 'actual': 4245, 'precision': 0.9144876325088339, 'recall': 0.9144876325088339, 'f1': 0.9144876325088339}, 'exact': {'correct': 4245, 'incorrect': 0, 'partial': 0, 'missed': 0, 'spurious': 0, 'possible': 4245, 'actual': 4245, 'precision': 1.0, 'recall': 1.0, 'f1': 1.0}}


# **############## END New Evaluation ##############**